### ISSUE TITLE
Invalid Authentication

### ISSUE THREAD

**Issue by Froddish** [andersevenrud/ha-nexa-bridge-x#31]
Hello,

I feel kind of stupid for asking but i just can't get this integration to work .. or atleast accept my authentication.

I bought a Nexa Bridge X, and everything works so far with the Bridge. Connected one of my previous devices without any issues (i am switching from Telldus since they more or less stopped support their own products).

i can turn it on and off without any issues either via cloud and locally.

however... for some reason i only get "invalid authentication" when i try to setup inside my home assistant. I have no idea what i am doing wrong.

i fill in the local ip for Nexa bridge (192.168.1.XXX) and then nexa/nexa and i get invalid authentication. if i enter the exact same information in any browser i get to the local web UI for the nexa bridge and everything works without any issues.

**WEB UI:**
![image](https://github.com/andersevenrud/ha-nexa-bridge-x/assets/116546869/18659b78-de1b-425b-a950-fedadca93881)

**Nexa Integration**
![image](https://github.com/andersevenrud/ha-nexa-bridge-x/assets/116546869/9f580ccb-dbb0-4f9d-a9f4-cfd4f26fb244)

**i have tried following:**
Restarted HA (soft and hard restart)
Restarted Nexa Bridge X
Switched from Wired to Wireless LAN on Nexa.
Tried to login with the cloud credentials and host: https://web.nexabridge.se/ which ofc was a long shot but i had to try.
Reinstalled the nexa bridge X integration in HACS
Tried an older version of the integration.
Tried the Legacy version.. 

I can ping the local ip from the terminal within homeassistant... 

Please help....

**Comment by andersevenrud** [comment]
Hi,

I haven't seen this error before, but I have a suspicion as to why it happens. Would you be comfortable installing the desktop application from https://www.postman.com/ ?

I need some information from your Nexa device in order to figure out what is going on, and with Postman you can retrieve this quite easily.

What you need to do:

1. Enter the URL of your nexa bridge
2. Make sure it is set to GET
3. Add "Digest Auth" with nexa/nexa login
4. Click "Send" and copy the response

<img width="1639" alt="Screenshot 2023-12-30 at 17 28 25" src="https://github.com/andersevenrud/ha-nexa-bridge-x/assets/161548/a8c9e435-cec4-4b0d-8d75-8f587ae4d181">

**NB** This could contain your IP address and/or location, so if you want to be anonymous, strip that out. It's not needed.

**Comment by andersevenrud** [comment]
Correction:

1. Enter this URL `http://192.168.0.193/v1/info` but replace the IP with yours
2. Make sure it is set to GET
3. Add "Digest Auth" with nexa/nexa login
4. Click "Send" and copy the response

<img width="1651" alt="Screenshot 2023-12-30 at 17 31 06" src="https://github.com/andersevenrud/ha-nexa-bridge-x/assets/161548/63d08878-27e2-41fb-bbc7-a99358a5019d">

**Comment by Froddish** [comment]
Hello!

Thanks for the quick response, here is what i got from the postman app:

{
    "systemType": "Bridge2",
    "builddate": "2020-11-09T12:30:37CET",
    "gitversion": "0ff44b4e0a22029229c00706aab2823b41b7155f",
    "version": "1.7.3",
    "gwid": "eeab06",
    "sunrise": "08:46",
    "sunset": "14:58",
    "location": {
        "status": "success",
        "ip": "81.225.65.40",
        "lat": 59.202133727970214,
        "lon": 17.63817956829072,
        "manualOverride": true
    },
    "currentTime": "2023-12-30T17:33:36+0100",
    "name": "Nexa Bridge X Frodd",
    "externalIp": "81.225.65.40",
    "remoteSupportPort": 0,
    "internalIp": "192.168.1.130",
    "zwaveRole": "Primary",
    "zwaveOnOtherNetwork": false,
    "nextChipFwVersion": "B1-1.2.2-191023-41e3183",
    "ok433": true,
    "zwaveOK": true,
    "cloudOK": true,
    "cloudLatency": 9,
    "wifiStatus": {
        "connected": true,
        "ssid": "Frodd",
        "address": "30:b5:c2:a2:f1:68"
    },
    "upgraded": false
}

**Comment by Froddish** [comment]
i wonder why i have the 1.7.3 version.. its new from the box today ...

**Comment by Froddish** [comment]
this is unf*cking beleiveable .. .a.d.as.d.. 

just tried for fun to add again... after the postman thingy
and guess what
![image](https://github.com/andersevenrud/ha-nexa-bridge-x/assets/116546869/f2cffd2a-cb1a-4922-a977-07f90927c2c1)

**Comment by Froddish** [comment]
Sorry for taking your time .. i really don't know what caused it to work again... however .. do you know if i can upgrade the firmware and if so .. how ?

**Comment by andersevenrud** [comment]
It seems like you have a X bridge running the legacy firmware. So I would highly recommend trying to update as you mention.

However, I'm not really sure how to do that. Maybe it's via their mobile app ?!

> Sorry for taking your time .. i really don't know what caused it to work again.

No problem. I would actually be very interested in what made it work.

I made it so that the integration checks if the firmware is correct for the bridge version (1/2) and gives off an "authentication error" if this is not the case.... so this actually might be a problem for others as well 🤔

**Comment by Froddish** [comment]
I really have no clue ... i went for the dishwasher and came back to read your response.. i will try to upgrade the firmware and i can write once i find out :)

**Comment by andersevenrud** [comment]
Great 👍

**Comment by Froddish** [comment]
In the phone app it says that i have version 2.4.1 .. i am so confused right now..
anyway.. happy new year!

**Comment by andersevenrud** [comment]
Very strange! Oh, well. At least it works now (?!)

Happy New Year :)
