### ISSUE TITLE
Dimmer properties

### ISSUE THREAD

**Issue by sonite** [andersevenrud/ha-nexa-bridge-x#37]
Is it really necessary for the default card in sensor integration, particularly with light sensors, to display both the light and the switch? 
Should we consider removing the switch? 

2nd consideration: that a Nexa dimmer might also be utilized for other applications than lights, what would be the best practice regarding representing the dimmer as a dimmer only?

![IMG_3164](https://github.com/andersevenrud/ha-nexa-bridge-x/assets/1986942/945790cc-de04-413a-b544-279b9e5a3265)

**Comment by andersevenrud** [comment]
Unless you've enabled `SWITCH_BINARY_SENSOR` in the config then this is what your Bridge reports.

Not much I can do about that.

**Comment by andersevenrud** [comment]
> what would be the best practice regarding representing the dimmer as a dimmer only?

Customised cards is the way to go. Either use the default configured ones and edit, or re-add a device and then set up a card from there.

The default cards can be a bit messy imo, so I use this one to group everything: https://github.com/benct/lovelace-multiple-entity-row ... albeit this requires manual configuration.

**Comment by andersevenrud** [comment]
I think I'll close this one because the integration should be transparent when it comes to reporting capabilities etc.

Adding custom behaviour/filtering etc could cause unwanted side-effects because in other scenarios.

The Nexa Bridge already messes with the capabilities of devices (and in many cases handicaps features. The provided API is not a "proper" Z-Wave compatible interface), so adding layers above this introduces all kinds of uncertainties in case of firmware updates and differences between different versions 😅

**Comment by sonite** [comment]
> I think I'll close this one because the integration should be transparent when it comes to reporting capabilities.
> 
> Adding custom behaviour/filtering etc. could cause unwanted side-effects in other scenarios.
> 
> The Nexa Bridge already messes with the capabilities of devices (and in many cases handicaps features. The provided API is not a "proper" Z-Wave compatible interface), so adding layers above this introduces all kinds of uncertainties in case of firmware updates and differences between versions 😅

Good choice. I forgot while configuring the sensor, Dimmer & On/Off properties could be chosen from.
